# Generated by Django 5.0.4 on 2024-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('emp_no', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('position', models.CharField(max_length=30)),
            ],
        ),
    ]
